#############################################################################
# Makefile for building: Progetto
# Generated by qmake (3.1) (Qt 6.4.2)
# Project:  Progetto.pro
# Template: app
# Command: /usr/bin/qmake6 -o Makefile Progetto.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I. -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Progetto1.0.0
DISTDIR = /home/pao/Progetto/.tmp/Progetto1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt6Widgets.so /usr/lib/x86_64-linux-gnu/libQt6Gui.so /usr/lib/x86_64-linux-gnu/libGLX.so /usr/lib/x86_64-linux-gnu/libOpenGL.so /usr/lib/x86_64-linux-gnu/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Interfaccia/AudioEditView.cpp \
		Interfaccia/BibliotecaMainWindow.cpp \
		Interfaccia/BookEditView.cpp \
		Interfaccia/DetailView.cpp \
		Interfaccia/DurationSlider.cpp \
		Interfaccia/EditView.cpp \
		Interfaccia/FilmEditView.cpp \
		Interfaccia/ListWidgetMedia.cpp \
		Interfaccia/ListWidgetMediaItem.cpp \
		Interfaccia/MagazineEditView.cpp \
		Interfaccia/MainView.cpp \
		Interfaccia/MultimediaEditView.cpp \
		Interfaccia/MusicSingleEditView.cpp \
		Interfaccia/MyToolBar.cpp \
		Interfaccia/PaperMediaEditView.cpp \
		Interfaccia/SearchInterface.cpp \
		Interfaccia/SearchListWidgetMedia.cpp \
		Interfaccia/test_interfaccia.cpp \
		Interfaccia/VideoEditView.cpp \
		modelloLogicoMedia/Audio.cpp \
		modelloLogicoMedia/Book.cpp \
		modelloLogicoMedia/Duration.cpp \
		modelloLogicoMedia/Film.cpp \
		modelloLogicoMedia/ISBN.cpp \
		modelloLogicoMedia/Magazine.cpp \
		modelloLogicoMedia/Media.cpp \
		modelloLogicoMedia/Multimedia.cpp \
		modelloLogicoMedia/MusicSingle.cpp \
		modelloLogicoMedia/PaperMedia.cpp \
		modelloLogicoMedia/test.cpp \
		modelloLogicoMedia/Video.cpp \
		Visitors/DetailVisitor.cpp \
		Visitors/EditVisitor.cpp \
		Visitors/FilterVisitor.cpp \
		Visitors/Query.cpp \
		Visitors/WidgetVisitor.cpp qrc_resources.cpp \
		moc_AudioEditView.cpp \
		moc_BibliotecaMainWindow.cpp \
		moc_BookEditView.cpp \
		moc_DetailView.cpp \
		moc_DurationSlider.cpp \
		moc_EditView.cpp \
		moc_FilmEditView.cpp \
		moc_ListWidgetMedia.cpp \
		moc_MagazineEditView.cpp \
		moc_MainView.cpp \
		moc_MultimediaEditView.cpp \
		moc_MusicSingleEditView.cpp \
		moc_MyToolBar.cpp \
		moc_PaperMediaEditView.cpp \
		moc_SearchInterface.cpp \
		moc_SearchListWidgetMedia.cpp \
		moc_VideoEditView.cpp
OBJECTS       = AudioEditView.o \
		BibliotecaMainWindow.o \
		BookEditView.o \
		DetailView.o \
		DurationSlider.o \
		EditView.o \
		FilmEditView.o \
		ListWidgetMedia.o \
		ListWidgetMediaItem.o \
		MagazineEditView.o \
		MainView.o \
		MultimediaEditView.o \
		MusicSingleEditView.o \
		MyToolBar.o \
		PaperMediaEditView.o \
		SearchInterface.o \
		SearchListWidgetMedia.o \
		test_interfaccia.o \
		VideoEditView.o \
		Audio.o \
		Book.o \
		Duration.o \
		Film.o \
		ISBN.o \
		Magazine.o \
		Media.o \
		Multimedia.o \
		MusicSingle.o \
		PaperMedia.o \
		test.o \
		Video.o \
		DetailVisitor.o \
		EditVisitor.o \
		FilterVisitor.o \
		Query.o \
		WidgetVisitor.o \
		qrc_resources.o \
		moc_AudioEditView.o \
		moc_BibliotecaMainWindow.o \
		moc_BookEditView.o \
		moc_DetailView.o \
		moc_DurationSlider.o \
		moc_EditView.o \
		moc_FilmEditView.o \
		moc_ListWidgetMedia.o \
		moc_MagazineEditView.o \
		moc_MainView.o \
		moc_MultimediaEditView.o \
		moc_MusicSingleEditView.o \
		moc_MyToolBar.o \
		moc_PaperMediaEditView.o \
		moc_SearchInterface.o \
		moc_SearchListWidgetMedia.o \
		moc_VideoEditView.o
DIST          = /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf \
		Progetto.pro Interfaccia/AudioEditView.h \
		Interfaccia/BibliotecaMainWindow.h \
		Interfaccia/BookEditView.h \
		Interfaccia/DetailView.h \
		Interfaccia/DurationSlider.h \
		Interfaccia/EditView.h \
		Interfaccia/FilmEditView.h \
		Interfaccia/ListWidgetMedia.h \
		Interfaccia/ListWidgetMediaItem.h \
		Interfaccia/MagazineEditView.h \
		Interfaccia/MainView.h \
		Interfaccia/MultimediaEditView.h \
		Interfaccia/MusicSingleEditView.h \
		Interfaccia/MyToolBar.h \
		Interfaccia/PaperMediaEditView.h \
		Interfaccia/SearchInterface.h \
		Interfaccia/SearchListWidgetMedia.h \
		Interfaccia/VideoEditView.h \
		modelloLogicoMedia/Audio.h \
		modelloLogicoMedia/Book.h \
		modelloLogicoMedia/Duration.h \
		modelloLogicoMedia/Film.h \
		modelloLogicoMedia/ISBN.h \
		modelloLogicoMedia/Magazine.h \
		modelloLogicoMedia/Media.h \
		modelloLogicoMedia/Multimedia.h \
		modelloLogicoMedia/MusicSingle.h \
		modelloLogicoMedia/PaperMedia.h \
		modelloLogicoMedia/Video.h \
		Observers/AbstractMediaObserver.h \
		Visitors/AbstractMediaVisitor.h \
		Visitors/DetailVisitor.h \
		Visitors/EditVisitor.h \
		Visitors/FilterVisitor.h \
		Visitors/Query.h \
		Visitors/WidgetVisitor.h \
		modelloLogicoMedia/Genre/AudioGenre.h \
		modelloLogicoMedia/Genre/BookGenre.h \
		modelloLogicoMedia/Genre/MagazineGenre.h \
		modelloLogicoMedia/Genre/VideoGenre.h Interfaccia/AudioEditView.cpp \
		Interfaccia/BibliotecaMainWindow.cpp \
		Interfaccia/BookEditView.cpp \
		Interfaccia/DetailView.cpp \
		Interfaccia/DurationSlider.cpp \
		Interfaccia/EditView.cpp \
		Interfaccia/FilmEditView.cpp \
		Interfaccia/ListWidgetMedia.cpp \
		Interfaccia/ListWidgetMediaItem.cpp \
		Interfaccia/MagazineEditView.cpp \
		Interfaccia/MainView.cpp \
		Interfaccia/MultimediaEditView.cpp \
		Interfaccia/MusicSingleEditView.cpp \
		Interfaccia/MyToolBar.cpp \
		Interfaccia/PaperMediaEditView.cpp \
		Interfaccia/SearchInterface.cpp \
		Interfaccia/SearchListWidgetMedia.cpp \
		Interfaccia/test_interfaccia.cpp \
		Interfaccia/VideoEditView.cpp \
		modelloLogicoMedia/Audio.cpp \
		modelloLogicoMedia/Book.cpp \
		modelloLogicoMedia/Duration.cpp \
		modelloLogicoMedia/Film.cpp \
		modelloLogicoMedia/ISBN.cpp \
		modelloLogicoMedia/Magazine.cpp \
		modelloLogicoMedia/Media.cpp \
		modelloLogicoMedia/Multimedia.cpp \
		modelloLogicoMedia/MusicSingle.cpp \
		modelloLogicoMedia/PaperMedia.cpp \
		modelloLogicoMedia/test.cpp \
		modelloLogicoMedia/Video.cpp \
		Visitors/DetailVisitor.cpp \
		Visitors/EditVisitor.cpp \
		Visitors/FilterVisitor.cpp \
		Visitors/Query.cpp \
		Visitors/WidgetVisitor.cpp
QMAKE_TARGET  = Progetto
DESTDIR       = 
TARGET        = Progetto


first: all
####### Build rules

Progetto:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Progetto.pro /usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf \
		Progetto.pro \
		resources.qrc \
		/usr/lib/x86_64-linux-gnu/libQt6Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Core.prl
	$(QMAKE) -o Makefile Progetto.pro
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf:
Progetto.pro:
resources.qrc:
/usr/lib/x86_64-linux-gnu/libQt6Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt6Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Progetto.pro

qmake_all: FORCE


all: Makefile Progetto

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Interfaccia/AudioEditView.h Interfaccia/BibliotecaMainWindow.h Interfaccia/BookEditView.h Interfaccia/DetailView.h Interfaccia/DurationSlider.h Interfaccia/EditView.h Interfaccia/FilmEditView.h Interfaccia/ListWidgetMedia.h Interfaccia/ListWidgetMediaItem.h Interfaccia/MagazineEditView.h Interfaccia/MainView.h Interfaccia/MultimediaEditView.h Interfaccia/MusicSingleEditView.h Interfaccia/MyToolBar.h Interfaccia/PaperMediaEditView.h Interfaccia/SearchInterface.h Interfaccia/SearchListWidgetMedia.h Interfaccia/VideoEditView.h modelloLogicoMedia/Audio.h modelloLogicoMedia/Book.h modelloLogicoMedia/Duration.h modelloLogicoMedia/Film.h modelloLogicoMedia/ISBN.h modelloLogicoMedia/Magazine.h modelloLogicoMedia/Media.h modelloLogicoMedia/Multimedia.h modelloLogicoMedia/MusicSingle.h modelloLogicoMedia/PaperMedia.h modelloLogicoMedia/Video.h Observers/AbstractMediaObserver.h Visitors/AbstractMediaVisitor.h Visitors/DetailVisitor.h Visitors/EditVisitor.h Visitors/FilterVisitor.h Visitors/Query.h Visitors/WidgetVisitor.h modelloLogicoMedia/Genre/AudioGenre.h modelloLogicoMedia/Genre/BookGenre.h modelloLogicoMedia/Genre/MagazineGenre.h modelloLogicoMedia/Genre/VideoGenre.h $(DISTDIR)/
	$(COPY_FILE) --parents Interfaccia/AudioEditView.cpp Interfaccia/BibliotecaMainWindow.cpp Interfaccia/BookEditView.cpp Interfaccia/DetailView.cpp Interfaccia/DurationSlider.cpp Interfaccia/EditView.cpp Interfaccia/FilmEditView.cpp Interfaccia/ListWidgetMedia.cpp Interfaccia/ListWidgetMediaItem.cpp Interfaccia/MagazineEditView.cpp Interfaccia/MainView.cpp Interfaccia/MultimediaEditView.cpp Interfaccia/MusicSingleEditView.cpp Interfaccia/MyToolBar.cpp Interfaccia/PaperMediaEditView.cpp Interfaccia/SearchInterface.cpp Interfaccia/SearchListWidgetMedia.cpp Interfaccia/test_interfaccia.cpp Interfaccia/VideoEditView.cpp modelloLogicoMedia/Audio.cpp modelloLogicoMedia/Book.cpp modelloLogicoMedia/Duration.cpp modelloLogicoMedia/Film.cpp modelloLogicoMedia/ISBN.cpp modelloLogicoMedia/Magazine.cpp modelloLogicoMedia/Media.cpp modelloLogicoMedia/Multimedia.cpp modelloLogicoMedia/MusicSingle.cpp modelloLogicoMedia/PaperMedia.cpp modelloLogicoMedia/test.cpp modelloLogicoMedia/Video.cpp Visitors/DetailVisitor.cpp Visitors/EditVisitor.cpp Visitors/FilterVisitor.cpp Visitors/Query.cpp Visitors/WidgetVisitor.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/lib/qt6/libexec/rcc \
		icons/elimina.png \
		icons/defaultImage.png \
		icons/book.png \
		icons/CD.png \
		icons/aggiungi.png \
		icons/film.png \
		icons/magazine.png
	/usr/lib/qt6/libexec/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -fPIC -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_AudioEditView.cpp moc_BibliotecaMainWindow.cpp moc_BookEditView.cpp moc_DetailView.cpp moc_DurationSlider.cpp moc_EditView.cpp moc_FilmEditView.cpp moc_ListWidgetMedia.cpp moc_MagazineEditView.cpp moc_MainView.cpp moc_MultimediaEditView.cpp moc_MusicSingleEditView.cpp moc_MyToolBar.cpp moc_PaperMediaEditView.cpp moc_SearchInterface.cpp moc_SearchListWidgetMedia.cpp moc_VideoEditView.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_AudioEditView.cpp moc_BibliotecaMainWindow.cpp moc_BookEditView.cpp moc_DetailView.cpp moc_DurationSlider.cpp moc_EditView.cpp moc_FilmEditView.cpp moc_ListWidgetMedia.cpp moc_MagazineEditView.cpp moc_MainView.cpp moc_MultimediaEditView.cpp moc_MusicSingleEditView.cpp moc_MyToolBar.cpp moc_PaperMediaEditView.cpp moc_SearchInterface.cpp moc_SearchListWidgetMedia.cpp moc_VideoEditView.cpp
moc_AudioEditView.cpp: Interfaccia/AudioEditView.h \
		Interfaccia/MultimediaEditView.h \
		Interfaccia/EditView.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		Interfaccia/DurationSlider.h \
		modelloLogicoMedia/Duration.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/pao/Progetto/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/pao/Progetto -I/home/pao/Progetto -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Interfaccia/AudioEditView.h -o moc_AudioEditView.cpp

moc_BibliotecaMainWindow.cpp: Interfaccia/BibliotecaMainWindow.h \
		Interfaccia/MyToolBar.h \
		Observers/AbstractMediaObserver.h \
		Interfaccia/SearchInterface.h \
		Interfaccia/SearchListWidgetMedia.h \
		Interfaccia/ListWidgetMedia.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		Visitors/Query.h \
		modelloLogicoMedia/Book.h \
		modelloLogicoMedia/PaperMedia.h \
		modelloLogicoMedia/ISBN.h \
		modelloLogicoMedia/Genre/BookGenre.h \
		modelloLogicoMedia/Magazine.h \
		modelloLogicoMedia/Genre/MagazineGenre.h \
		modelloLogicoMedia/MusicSingle.h \
		modelloLogicoMedia/Audio.h \
		modelloLogicoMedia/Multimedia.h \
		modelloLogicoMedia/Duration.h \
		modelloLogicoMedia/Genre/AudioGenre.h \
		modelloLogicoMedia/Film.h \
		modelloLogicoMedia/Video.h \
		modelloLogicoMedia/Genre/VideoGenre.h \
		Interfaccia/MainView.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/pao/Progetto/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/pao/Progetto -I/home/pao/Progetto -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Interfaccia/BibliotecaMainWindow.h -o moc_BibliotecaMainWindow.cpp

moc_BookEditView.cpp: Interfaccia/BookEditView.h \
		Interfaccia/PaperMediaEditView.h \
		Interfaccia/EditView.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		modelloLogicoMedia/Book.h \
		modelloLogicoMedia/PaperMedia.h \
		modelloLogicoMedia/ISBN.h \
		modelloLogicoMedia/Genre/BookGenre.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/pao/Progetto/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/pao/Progetto -I/home/pao/Progetto -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Interfaccia/BookEditView.h -o moc_BookEditView.cpp

moc_DetailView.cpp: Interfaccia/DetailView.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/pao/Progetto/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/pao/Progetto -I/home/pao/Progetto -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Interfaccia/DetailView.h -o moc_DetailView.cpp

moc_DurationSlider.cpp: Interfaccia/DurationSlider.h \
		modelloLogicoMedia/Duration.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/pao/Progetto/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/pao/Progetto -I/home/pao/Progetto -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Interfaccia/DurationSlider.h -o moc_DurationSlider.cpp

moc_EditView.cpp: Interfaccia/EditView.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/pao/Progetto/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/pao/Progetto -I/home/pao/Progetto -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Interfaccia/EditView.h -o moc_EditView.cpp

moc_FilmEditView.cpp: Interfaccia/FilmEditView.h \
		Interfaccia/VideoEditView.h \
		Interfaccia/MultimediaEditView.h \
		Interfaccia/EditView.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		Interfaccia/DurationSlider.h \
		modelloLogicoMedia/Duration.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/pao/Progetto/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/pao/Progetto -I/home/pao/Progetto -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Interfaccia/FilmEditView.h -o moc_FilmEditView.cpp

moc_ListWidgetMedia.cpp: Interfaccia/ListWidgetMedia.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/pao/Progetto/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/pao/Progetto -I/home/pao/Progetto -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Interfaccia/ListWidgetMedia.h -o moc_ListWidgetMedia.cpp

moc_MagazineEditView.cpp: Interfaccia/MagazineEditView.h \
		Interfaccia/PaperMediaEditView.h \
		Interfaccia/EditView.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		modelloLogicoMedia/Magazine.h \
		modelloLogicoMedia/PaperMedia.h \
		modelloLogicoMedia/Genre/MagazineGenre.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/pao/Progetto/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/pao/Progetto -I/home/pao/Progetto -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Interfaccia/MagazineEditView.h -o moc_MagazineEditView.cpp

moc_MainView.cpp: Interfaccia/MainView.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/pao/Progetto/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/pao/Progetto -I/home/pao/Progetto -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Interfaccia/MainView.h -o moc_MainView.cpp

moc_MultimediaEditView.cpp: Interfaccia/MultimediaEditView.h \
		Interfaccia/EditView.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		Interfaccia/DurationSlider.h \
		modelloLogicoMedia/Duration.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/pao/Progetto/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/pao/Progetto -I/home/pao/Progetto -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Interfaccia/MultimediaEditView.h -o moc_MultimediaEditView.cpp

moc_MusicSingleEditView.cpp: Interfaccia/MusicSingleEditView.h \
		Interfaccia/AudioEditView.h \
		Interfaccia/MultimediaEditView.h \
		Interfaccia/EditView.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		Interfaccia/DurationSlider.h \
		modelloLogicoMedia/Duration.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/pao/Progetto/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/pao/Progetto -I/home/pao/Progetto -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Interfaccia/MusicSingleEditView.h -o moc_MusicSingleEditView.cpp

moc_MyToolBar.cpp: Interfaccia/MyToolBar.h \
		Observers/AbstractMediaObserver.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/pao/Progetto/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/pao/Progetto -I/home/pao/Progetto -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Interfaccia/MyToolBar.h -o moc_MyToolBar.cpp

moc_PaperMediaEditView.cpp: Interfaccia/PaperMediaEditView.h \
		Interfaccia/EditView.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/pao/Progetto/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/pao/Progetto -I/home/pao/Progetto -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Interfaccia/PaperMediaEditView.h -o moc_PaperMediaEditView.cpp

moc_SearchInterface.cpp: Interfaccia/SearchInterface.h \
		Interfaccia/SearchListWidgetMedia.h \
		Interfaccia/ListWidgetMedia.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		Visitors/Query.h \
		modelloLogicoMedia/Book.h \
		modelloLogicoMedia/PaperMedia.h \
		modelloLogicoMedia/ISBN.h \
		modelloLogicoMedia/Genre/BookGenre.h \
		modelloLogicoMedia/Magazine.h \
		modelloLogicoMedia/Genre/MagazineGenre.h \
		modelloLogicoMedia/MusicSingle.h \
		modelloLogicoMedia/Audio.h \
		modelloLogicoMedia/Multimedia.h \
		modelloLogicoMedia/Duration.h \
		modelloLogicoMedia/Genre/AudioGenre.h \
		modelloLogicoMedia/Film.h \
		modelloLogicoMedia/Video.h \
		modelloLogicoMedia/Genre/VideoGenre.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/pao/Progetto/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/pao/Progetto -I/home/pao/Progetto -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Interfaccia/SearchInterface.h -o moc_SearchInterface.cpp

moc_SearchListWidgetMedia.cpp: Interfaccia/SearchListWidgetMedia.h \
		Interfaccia/ListWidgetMedia.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		Visitors/Query.h \
		modelloLogicoMedia/Book.h \
		modelloLogicoMedia/PaperMedia.h \
		modelloLogicoMedia/ISBN.h \
		modelloLogicoMedia/Genre/BookGenre.h \
		modelloLogicoMedia/Magazine.h \
		modelloLogicoMedia/Genre/MagazineGenre.h \
		modelloLogicoMedia/MusicSingle.h \
		modelloLogicoMedia/Audio.h \
		modelloLogicoMedia/Multimedia.h \
		modelloLogicoMedia/Duration.h \
		modelloLogicoMedia/Genre/AudioGenre.h \
		modelloLogicoMedia/Film.h \
		modelloLogicoMedia/Video.h \
		modelloLogicoMedia/Genre/VideoGenre.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/pao/Progetto/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/pao/Progetto -I/home/pao/Progetto -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Interfaccia/SearchListWidgetMedia.h -o moc_SearchListWidgetMedia.cpp

moc_VideoEditView.cpp: Interfaccia/VideoEditView.h \
		Interfaccia/MultimediaEditView.h \
		Interfaccia/EditView.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		Interfaccia/DurationSlider.h \
		modelloLogicoMedia/Duration.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/pao/Progetto/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/pao/Progetto -I/home/pao/Progetto -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Interfaccia/VideoEditView.h -o moc_VideoEditView.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

AudioEditView.o: Interfaccia/AudioEditView.cpp Interfaccia/AudioEditView.h \
		Interfaccia/MultimediaEditView.h \
		Interfaccia/EditView.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		Interfaccia/DurationSlider.h \
		modelloLogicoMedia/Duration.h \
		modelloLogicoMedia/Audio.h \
		modelloLogicoMedia/Multimedia.h \
		modelloLogicoMedia/Genre/AudioGenre.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AudioEditView.o Interfaccia/AudioEditView.cpp

BibliotecaMainWindow.o: Interfaccia/BibliotecaMainWindow.cpp Interfaccia/BibliotecaMainWindow.h \
		Interfaccia/MyToolBar.h \
		Observers/AbstractMediaObserver.h \
		Interfaccia/SearchInterface.h \
		Interfaccia/SearchListWidgetMedia.h \
		Interfaccia/ListWidgetMedia.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		Visitors/Query.h \
		modelloLogicoMedia/Book.h \
		modelloLogicoMedia/PaperMedia.h \
		modelloLogicoMedia/ISBN.h \
		modelloLogicoMedia/Genre/BookGenre.h \
		modelloLogicoMedia/Magazine.h \
		modelloLogicoMedia/Genre/MagazineGenre.h \
		modelloLogicoMedia/MusicSingle.h \
		modelloLogicoMedia/Audio.h \
		modelloLogicoMedia/Multimedia.h \
		modelloLogicoMedia/Duration.h \
		modelloLogicoMedia/Genre/AudioGenre.h \
		modelloLogicoMedia/Film.h \
		modelloLogicoMedia/Video.h \
		modelloLogicoMedia/Genre/VideoGenre.h \
		Interfaccia/MainView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BibliotecaMainWindow.o Interfaccia/BibliotecaMainWindow.cpp

BookEditView.o: Interfaccia/BookEditView.cpp Interfaccia/BookEditView.h \
		Interfaccia/PaperMediaEditView.h \
		Interfaccia/EditView.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		modelloLogicoMedia/Book.h \
		modelloLogicoMedia/PaperMedia.h \
		modelloLogicoMedia/ISBN.h \
		modelloLogicoMedia/Genre/BookGenre.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BookEditView.o Interfaccia/BookEditView.cpp

DetailView.o: Interfaccia/DetailView.cpp Interfaccia/DetailView.h \
		modelloLogicoMedia/Book.h \
		modelloLogicoMedia/PaperMedia.h \
		modelloLogicoMedia/Media.h \
		modelloLogicoMedia/ISBN.h \
		modelloLogicoMedia/Genre/BookGenre.h \
		modelloLogicoMedia/Magazine.h \
		modelloLogicoMedia/Genre/MagazineGenre.h \
		modelloLogicoMedia/MusicSingle.h \
		modelloLogicoMedia/Audio.h \
		modelloLogicoMedia/Multimedia.h \
		modelloLogicoMedia/Duration.h \
		modelloLogicoMedia/Genre/AudioGenre.h \
		modelloLogicoMedia/Film.h \
		modelloLogicoMedia/Video.h \
		modelloLogicoMedia/Genre/VideoGenre.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DetailView.o Interfaccia/DetailView.cpp

DurationSlider.o: Interfaccia/DurationSlider.cpp Interfaccia/DurationSlider.h \
		modelloLogicoMedia/Duration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DurationSlider.o Interfaccia/DurationSlider.cpp

EditView.o: Interfaccia/EditView.cpp Interfaccia/EditView.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EditView.o Interfaccia/EditView.cpp

FilmEditView.o: Interfaccia/FilmEditView.cpp Interfaccia/FilmEditView.h \
		Interfaccia/VideoEditView.h \
		Interfaccia/MultimediaEditView.h \
		Interfaccia/EditView.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		Interfaccia/DurationSlider.h \
		modelloLogicoMedia/Duration.h \
		modelloLogicoMedia/Film.h \
		modelloLogicoMedia/Video.h \
		modelloLogicoMedia/Multimedia.h \
		modelloLogicoMedia/Genre/VideoGenre.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FilmEditView.o Interfaccia/FilmEditView.cpp

ListWidgetMedia.o: Interfaccia/ListWidgetMedia.cpp Interfaccia/ListWidgetMedia.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ListWidgetMedia.o Interfaccia/ListWidgetMedia.cpp

ListWidgetMediaItem.o: Interfaccia/ListWidgetMediaItem.cpp Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ListWidgetMediaItem.o Interfaccia/ListWidgetMediaItem.cpp

MagazineEditView.o: Interfaccia/MagazineEditView.cpp Interfaccia/MagazineEditView.h \
		Interfaccia/PaperMediaEditView.h \
		Interfaccia/EditView.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		modelloLogicoMedia/Magazine.h \
		modelloLogicoMedia/PaperMedia.h \
		modelloLogicoMedia/Genre/MagazineGenre.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MagazineEditView.o Interfaccia/MagazineEditView.cpp

MainView.o: Interfaccia/MainView.cpp Interfaccia/MainView.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		Interfaccia/BookEditView.h \
		Interfaccia/PaperMediaEditView.h \
		Interfaccia/EditView.h \
		modelloLogicoMedia/Book.h \
		modelloLogicoMedia/PaperMedia.h \
		modelloLogicoMedia/ISBN.h \
		modelloLogicoMedia/Genre/BookGenre.h \
		Interfaccia/MagazineEditView.h \
		modelloLogicoMedia/Magazine.h \
		modelloLogicoMedia/Genre/MagazineGenre.h \
		Interfaccia/MusicSingleEditView.h \
		Interfaccia/AudioEditView.h \
		Interfaccia/MultimediaEditView.h \
		Interfaccia/DurationSlider.h \
		modelloLogicoMedia/Duration.h \
		Interfaccia/FilmEditView.h \
		Interfaccia/VideoEditView.h \
		Visitors/EditVisitor.h \
		Visitors/WidgetVisitor.h \
		Visitors/AbstractMediaVisitor.h \
		Visitors/DetailVisitor.h \
		Interfaccia/DetailView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainView.o Interfaccia/MainView.cpp

MultimediaEditView.o: Interfaccia/MultimediaEditView.cpp Interfaccia/MultimediaEditView.h \
		Interfaccia/EditView.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		Interfaccia/DurationSlider.h \
		modelloLogicoMedia/Duration.h \
		modelloLogicoMedia/Multimedia.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MultimediaEditView.o Interfaccia/MultimediaEditView.cpp

MusicSingleEditView.o: Interfaccia/MusicSingleEditView.cpp Interfaccia/MusicSingleEditView.h \
		Interfaccia/AudioEditView.h \
		Interfaccia/MultimediaEditView.h \
		Interfaccia/EditView.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		Interfaccia/DurationSlider.h \
		modelloLogicoMedia/Duration.h \
		modelloLogicoMedia/MusicSingle.h \
		modelloLogicoMedia/Audio.h \
		modelloLogicoMedia/Multimedia.h \
		modelloLogicoMedia/Genre/AudioGenre.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MusicSingleEditView.o Interfaccia/MusicSingleEditView.cpp

MyToolBar.o: Interfaccia/MyToolBar.cpp Interfaccia/MyToolBar.h \
		Observers/AbstractMediaObserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MyToolBar.o Interfaccia/MyToolBar.cpp

PaperMediaEditView.o: Interfaccia/PaperMediaEditView.cpp Interfaccia/PaperMediaEditView.h \
		Interfaccia/EditView.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		modelloLogicoMedia/PaperMedia.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PaperMediaEditView.o Interfaccia/PaperMediaEditView.cpp

SearchInterface.o: Interfaccia/SearchInterface.cpp Interfaccia/SearchInterface.h \
		Interfaccia/SearchListWidgetMedia.h \
		Interfaccia/ListWidgetMedia.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		Visitors/Query.h \
		modelloLogicoMedia/Book.h \
		modelloLogicoMedia/PaperMedia.h \
		modelloLogicoMedia/ISBN.h \
		modelloLogicoMedia/Genre/BookGenre.h \
		modelloLogicoMedia/Magazine.h \
		modelloLogicoMedia/Genre/MagazineGenre.h \
		modelloLogicoMedia/MusicSingle.h \
		modelloLogicoMedia/Audio.h \
		modelloLogicoMedia/Multimedia.h \
		modelloLogicoMedia/Duration.h \
		modelloLogicoMedia/Genre/AudioGenre.h \
		modelloLogicoMedia/Film.h \
		modelloLogicoMedia/Video.h \
		modelloLogicoMedia/Genre/VideoGenre.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SearchInterface.o Interfaccia/SearchInterface.cpp

SearchListWidgetMedia.o: Interfaccia/SearchListWidgetMedia.cpp Interfaccia/SearchListWidgetMedia.h \
		Interfaccia/ListWidgetMedia.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		Visitors/Query.h \
		modelloLogicoMedia/Book.h \
		modelloLogicoMedia/PaperMedia.h \
		modelloLogicoMedia/ISBN.h \
		modelloLogicoMedia/Genre/BookGenre.h \
		modelloLogicoMedia/Magazine.h \
		modelloLogicoMedia/Genre/MagazineGenre.h \
		modelloLogicoMedia/MusicSingle.h \
		modelloLogicoMedia/Audio.h \
		modelloLogicoMedia/Multimedia.h \
		modelloLogicoMedia/Duration.h \
		modelloLogicoMedia/Genre/AudioGenre.h \
		modelloLogicoMedia/Film.h \
		modelloLogicoMedia/Video.h \
		modelloLogicoMedia/Genre/VideoGenre.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SearchListWidgetMedia.o Interfaccia/SearchListWidgetMedia.cpp

test_interfaccia.o: Interfaccia/test_interfaccia.cpp Interfaccia/BibliotecaMainWindow.h \
		Interfaccia/MyToolBar.h \
		Observers/AbstractMediaObserver.h \
		Interfaccia/SearchInterface.h \
		Interfaccia/SearchListWidgetMedia.h \
		Interfaccia/ListWidgetMedia.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		Visitors/Query.h \
		modelloLogicoMedia/Book.h \
		modelloLogicoMedia/PaperMedia.h \
		modelloLogicoMedia/ISBN.h \
		modelloLogicoMedia/Genre/BookGenre.h \
		modelloLogicoMedia/Magazine.h \
		modelloLogicoMedia/Genre/MagazineGenre.h \
		modelloLogicoMedia/MusicSingle.h \
		modelloLogicoMedia/Audio.h \
		modelloLogicoMedia/Multimedia.h \
		modelloLogicoMedia/Duration.h \
		modelloLogicoMedia/Genre/AudioGenre.h \
		modelloLogicoMedia/Film.h \
		modelloLogicoMedia/Video.h \
		modelloLogicoMedia/Genre/VideoGenre.h \
		Interfaccia/MainView.h \
		Interfaccia/BookEditView.h \
		Interfaccia/PaperMediaEditView.h \
		Interfaccia/EditView.h \
		Interfaccia/MagazineEditView.h \
		Interfaccia/MusicSingleEditView.h \
		Interfaccia/AudioEditView.h \
		Interfaccia/MultimediaEditView.h \
		Interfaccia/DurationSlider.h \
		Interfaccia/FilmEditView.h \
		Interfaccia/VideoEditView.h \
		Interfaccia/DetailView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test_interfaccia.o Interfaccia/test_interfaccia.cpp

VideoEditView.o: Interfaccia/VideoEditView.cpp Interfaccia/VideoEditView.h \
		Interfaccia/MultimediaEditView.h \
		Interfaccia/EditView.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		Interfaccia/DurationSlider.h \
		modelloLogicoMedia/Duration.h \
		modelloLogicoMedia/Video.h \
		modelloLogicoMedia/Multimedia.h \
		modelloLogicoMedia/Genre/VideoGenre.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VideoEditView.o Interfaccia/VideoEditView.cpp

Audio.o: modelloLogicoMedia/Audio.cpp modelloLogicoMedia/Audio.h \
		modelloLogicoMedia/Multimedia.h \
		modelloLogicoMedia/Media.h \
		modelloLogicoMedia/Duration.h \
		modelloLogicoMedia/Genre/AudioGenre.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Audio.o modelloLogicoMedia/Audio.cpp

Book.o: modelloLogicoMedia/Book.cpp modelloLogicoMedia/Book.h \
		modelloLogicoMedia/PaperMedia.h \
		modelloLogicoMedia/Media.h \
		modelloLogicoMedia/ISBN.h \
		modelloLogicoMedia/Genre/BookGenre.h \
		Visitors/AbstractMediaVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Book.o modelloLogicoMedia/Book.cpp

Duration.o: modelloLogicoMedia/Duration.cpp modelloLogicoMedia/Duration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Duration.o modelloLogicoMedia/Duration.cpp

Film.o: modelloLogicoMedia/Film.cpp modelloLogicoMedia/Film.h \
		modelloLogicoMedia/Video.h \
		modelloLogicoMedia/Multimedia.h \
		modelloLogicoMedia/Media.h \
		modelloLogicoMedia/Duration.h \
		modelloLogicoMedia/Genre/VideoGenre.h \
		Visitors/AbstractMediaVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Film.o modelloLogicoMedia/Film.cpp

ISBN.o: modelloLogicoMedia/ISBN.cpp modelloLogicoMedia/ISBN.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ISBN.o modelloLogicoMedia/ISBN.cpp

Magazine.o: modelloLogicoMedia/Magazine.cpp modelloLogicoMedia/Magazine.h \
		modelloLogicoMedia/PaperMedia.h \
		modelloLogicoMedia/Media.h \
		modelloLogicoMedia/Genre/MagazineGenre.h \
		Visitors/AbstractMediaVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Magazine.o modelloLogicoMedia/Magazine.cpp

Media.o: modelloLogicoMedia/Media.cpp modelloLogicoMedia/Media.h \
		Observers/AbstractMediaObserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Media.o modelloLogicoMedia/Media.cpp

Multimedia.o: modelloLogicoMedia/Multimedia.cpp modelloLogicoMedia/Multimedia.h \
		modelloLogicoMedia/Media.h \
		modelloLogicoMedia/Duration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Multimedia.o modelloLogicoMedia/Multimedia.cpp

MusicSingle.o: modelloLogicoMedia/MusicSingle.cpp modelloLogicoMedia/MusicSingle.h \
		modelloLogicoMedia/Audio.h \
		modelloLogicoMedia/Multimedia.h \
		modelloLogicoMedia/Media.h \
		modelloLogicoMedia/Duration.h \
		modelloLogicoMedia/Genre/AudioGenre.h \
		Visitors/AbstractMediaVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MusicSingle.o modelloLogicoMedia/MusicSingle.cpp

PaperMedia.o: modelloLogicoMedia/PaperMedia.cpp modelloLogicoMedia/PaperMedia.h \
		modelloLogicoMedia/Media.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PaperMedia.o modelloLogicoMedia/PaperMedia.cpp

test.o: modelloLogicoMedia/test.cpp modelloLogicoMedia/Book.h \
		modelloLogicoMedia/PaperMedia.h \
		modelloLogicoMedia/Media.h \
		modelloLogicoMedia/ISBN.h \
		modelloLogicoMedia/Genre/BookGenre.h \
		modelloLogicoMedia/Magazine.h \
		modelloLogicoMedia/Genre/MagazineGenre.h \
		modelloLogicoMedia/MusicSingle.h \
		modelloLogicoMedia/Audio.h \
		modelloLogicoMedia/Multimedia.h \
		modelloLogicoMedia/Duration.h \
		modelloLogicoMedia/Genre/AudioGenre.h \
		modelloLogicoMedia/Film.h \
		modelloLogicoMedia/Video.h \
		modelloLogicoMedia/Genre/VideoGenre.h \
		Visitors/Query.h \
		Visitors/FilterVisitor.h \
		Visitors/AbstractMediaVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test.o modelloLogicoMedia/test.cpp

Video.o: modelloLogicoMedia/Video.cpp modelloLogicoMedia/Video.h \
		modelloLogicoMedia/Multimedia.h \
		modelloLogicoMedia/Media.h \
		modelloLogicoMedia/Duration.h \
		modelloLogicoMedia/Genre/VideoGenre.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Video.o modelloLogicoMedia/Video.cpp

DetailVisitor.o: Visitors/DetailVisitor.cpp Visitors/DetailVisitor.h \
		Interfaccia/DetailView.h \
		Visitors/WidgetVisitor.h \
		Visitors/AbstractMediaVisitor.h \
		modelloLogicoMedia/Book.h \
		modelloLogicoMedia/PaperMedia.h \
		modelloLogicoMedia/Media.h \
		modelloLogicoMedia/ISBN.h \
		modelloLogicoMedia/Genre/BookGenre.h \
		modelloLogicoMedia/Magazine.h \
		modelloLogicoMedia/Genre/MagazineGenre.h \
		modelloLogicoMedia/MusicSingle.h \
		modelloLogicoMedia/Audio.h \
		modelloLogicoMedia/Multimedia.h \
		modelloLogicoMedia/Duration.h \
		modelloLogicoMedia/Genre/AudioGenre.h \
		modelloLogicoMedia/Film.h \
		modelloLogicoMedia/Video.h \
		modelloLogicoMedia/Genre/VideoGenre.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DetailVisitor.o Visitors/DetailVisitor.cpp

EditVisitor.o: Visitors/EditVisitor.cpp Visitors/EditVisitor.h \
		Visitors/WidgetVisitor.h \
		Visitors/AbstractMediaVisitor.h \
		Interfaccia/BookEditView.h \
		Interfaccia/PaperMediaEditView.h \
		Interfaccia/EditView.h \
		Interfaccia/ListWidgetMediaItem.h \
		modelloLogicoMedia/Media.h \
		modelloLogicoMedia/Book.h \
		modelloLogicoMedia/PaperMedia.h \
		modelloLogicoMedia/ISBN.h \
		modelloLogicoMedia/Genre/BookGenre.h \
		Interfaccia/MagazineEditView.h \
		modelloLogicoMedia/Magazine.h \
		modelloLogicoMedia/Genre/MagazineGenre.h \
		Interfaccia/MusicSingleEditView.h \
		Interfaccia/AudioEditView.h \
		Interfaccia/MultimediaEditView.h \
		Interfaccia/DurationSlider.h \
		modelloLogicoMedia/Duration.h \
		Interfaccia/FilmEditView.h \
		Interfaccia/VideoEditView.h \
		modelloLogicoMedia/MusicSingle.h \
		modelloLogicoMedia/Audio.h \
		modelloLogicoMedia/Multimedia.h \
		modelloLogicoMedia/Genre/AudioGenre.h \
		modelloLogicoMedia/Film.h \
		modelloLogicoMedia/Video.h \
		modelloLogicoMedia/Genre/VideoGenre.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EditVisitor.o Visitors/EditVisitor.cpp

FilterVisitor.o: Visitors/FilterVisitor.cpp modelloLogicoMedia/Book.h \
		modelloLogicoMedia/PaperMedia.h \
		modelloLogicoMedia/Media.h \
		modelloLogicoMedia/ISBN.h \
		modelloLogicoMedia/Genre/BookGenre.h \
		modelloLogicoMedia/Magazine.h \
		modelloLogicoMedia/Genre/MagazineGenre.h \
		modelloLogicoMedia/MusicSingle.h \
		modelloLogicoMedia/Audio.h \
		modelloLogicoMedia/Multimedia.h \
		modelloLogicoMedia/Duration.h \
		modelloLogicoMedia/Genre/AudioGenre.h \
		modelloLogicoMedia/Film.h \
		modelloLogicoMedia/Video.h \
		modelloLogicoMedia/Genre/VideoGenre.h \
		Visitors/FilterVisitor.h \
		Visitors/AbstractMediaVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FilterVisitor.o Visitors/FilterVisitor.cpp

Query.o: Visitors/Query.cpp Visitors/Query.h \
		modelloLogicoMedia/Book.h \
		modelloLogicoMedia/PaperMedia.h \
		modelloLogicoMedia/Media.h \
		modelloLogicoMedia/ISBN.h \
		modelloLogicoMedia/Genre/BookGenre.h \
		modelloLogicoMedia/Magazine.h \
		modelloLogicoMedia/Genre/MagazineGenre.h \
		modelloLogicoMedia/MusicSingle.h \
		modelloLogicoMedia/Audio.h \
		modelloLogicoMedia/Multimedia.h \
		modelloLogicoMedia/Duration.h \
		modelloLogicoMedia/Genre/AudioGenre.h \
		modelloLogicoMedia/Film.h \
		modelloLogicoMedia/Video.h \
		modelloLogicoMedia/Genre/VideoGenre.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Query.o Visitors/Query.cpp

WidgetVisitor.o: Visitors/WidgetVisitor.cpp Visitors/WidgetVisitor.h \
		Visitors/AbstractMediaVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WidgetVisitor.o Visitors/WidgetVisitor.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_AudioEditView.o: moc_AudioEditView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AudioEditView.o moc_AudioEditView.cpp

moc_BibliotecaMainWindow.o: moc_BibliotecaMainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_BibliotecaMainWindow.o moc_BibliotecaMainWindow.cpp

moc_BookEditView.o: moc_BookEditView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_BookEditView.o moc_BookEditView.cpp

moc_DetailView.o: moc_DetailView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DetailView.o moc_DetailView.cpp

moc_DurationSlider.o: moc_DurationSlider.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DurationSlider.o moc_DurationSlider.cpp

moc_EditView.o: moc_EditView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_EditView.o moc_EditView.cpp

moc_FilmEditView.o: moc_FilmEditView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FilmEditView.o moc_FilmEditView.cpp

moc_ListWidgetMedia.o: moc_ListWidgetMedia.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ListWidgetMedia.o moc_ListWidgetMedia.cpp

moc_MagazineEditView.o: moc_MagazineEditView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MagazineEditView.o moc_MagazineEditView.cpp

moc_MainView.o: moc_MainView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainView.o moc_MainView.cpp

moc_MultimediaEditView.o: moc_MultimediaEditView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MultimediaEditView.o moc_MultimediaEditView.cpp

moc_MusicSingleEditView.o: moc_MusicSingleEditView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MusicSingleEditView.o moc_MusicSingleEditView.cpp

moc_MyToolBar.o: moc_MyToolBar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MyToolBar.o moc_MyToolBar.cpp

moc_PaperMediaEditView.o: moc_PaperMediaEditView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PaperMediaEditView.o moc_PaperMediaEditView.cpp

moc_SearchInterface.o: moc_SearchInterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SearchInterface.o moc_SearchInterface.cpp

moc_SearchListWidgetMedia.o: moc_SearchListWidgetMedia.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SearchListWidgetMedia.o moc_SearchListWidgetMedia.cpp

moc_VideoEditView.o: moc_VideoEditView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_VideoEditView.o moc_VideoEditView.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

